### ISSUE TITLE
Can't run on a CPU without updating the code

### ISSUE THREAD

**Issue by PJ-Finlay** [gordicaleksa/pytorch-deepdream#3]
I'm making a pull request to fix this.

**Comment by PJ-Finlay** [comment]
#4 Here it is. Thanks for making this library! I spent an entire day trying to get caffe installed before giving up. This just works and seems to produce higher quality images then most of the DeepDreams out there.

**Comment by gordicaleksa** [comment]
Hey!

First of all, I'm sorry I unfortunately rarely have the time to address the PRs.

Having said that, the project just went through some serious refactoring and I've added new features as well:

* it's now completely command-line friendly (I tested it myself)
* I've added a Jupyter Notebook which is probably THE BEST place to start
* I've refactored many functions and added additional explanations and comments
* It works on CPU (I haven't seen your PR actually haha)

Please pull the newest changes, test them and let me know how it went!

If everything's ok I'm closing this issue. I'll take a look at your PR whether you have some orthogonal changes.

**Comment by gordicaleksa** [comment]
Just went through your PR, I solved the CPU problem you had in my recent refactor! And I've tested it.

The "fps" argument you added is a good idea! I'll push it myself, it'll be faster.

Thank you for your PR and again I'm sorry I didn't have the time to address it before.

My workflow is the following: if there are some tasks on my backlog for one of my GitHub projects, I do them first, and only later do I address the PRs - since this is not a huge project.

I strongly encourage people to create PRs and even though this time I haven't merged your changes I appreciate it.
